language: php

compiler:
  - gcc
  - clang

os:
  - linux

php:
  - 7.0
  - 7.1
  - 7.2

notifications:
  email: itwujunze@gmail.com

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./travis/compile.sh

# Run PHPs run-tests.php
script:
  - ./travis/run-test.sh